# docs/stops-and-routes.md.

stops:
  - id: reid-library
    name: Reid Library
    latitude: -31.97901221771226
    longitude: 115.8183554056777

  - id: civ-mech
    name: Outside Civil and Mechanical Engineering
    latitude: -31.980743857374474
    longitude: 115.81720535774184

  - id: business-school   # this is the actual business school car park and not the location on the current gps track the buses follow.
    name: Outside the Business School
    latitude: -31.985583444723204
    longitude: 115.82089500479223

  - id: guild-village
    name: Intersection of Saw Promenade and Graduates walk
    latitude: -31.9806087
    longitude: 115.8187129

  - id: barry-marshall
    name: Barry J Marshall Library
    latitude: -31.9830579
    longitude: 115.8187461
  
  - id: guild-village
    name: Intersection of Saw Promenade and Graduates walk
    latitude: -31.9806087
    longitude: 115.8187129

  - id: ezone-central
    name: Path to E-zone from James oval
    latitude: -31.9797545
    longitude: 115.8171536

  - id: bilya-marlee
    name: underwood parade outside Bilya Marlee
    latitude: -31.9828347
    longitude: 115.8201390
  
  - id: sports-science
    name: Saw promenade at Human movement lab/ UWA aquatic center 
    latitude: -31.9848357
    longitude: 115.8187636

  - id: marine-research
    name: Between IOMRC and Civ & Mechanical Engineering 
    latitude: -31.9813149
    longitude: 115.8165538


routes:
  # PLACEHOLDER
  - id: campus-loop
    name: Campus loop
    colour: "#d4741f"
    loop: true
    stops: [reid-library, civ-mech, business-school]
